global:
  scrape_interval: 15s
scrape_configs:
  - job_name: default_federate
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__=~"node_.*"}'
    static_configs:
      - targets:
          - "10.1.1.10:9090"
